const countryStats = [
  {
    name: 'United States',
    average: 79,
    male: 76,
    female: 81,
  },
  {
    name: 'Afghanistan',
    average: 61,
    male: 60,
    female: 62,
  },
  {
    name: 'Albania',
    average: 78,
    male: 76,
    female: 80,
  },
  {
    name: 'Algeria',
    average: 74,
    male: 72,
    female: 77,
  },
  {
    name: 'Angola',
    average: 52,
    male: 50,
    female: 53,
  },
  {
    name: 'Antigua and Barbuda',
    average: 77,
    male: 74,
    female: 80,
  },
  {
    name: 'Argentina',
    average: 77,
    male: 73,
    female: 80,
  },
  {
    name: 'Armenia',
    average: 75,
    male: 72,
    female: 78,
  },
  {
    name: 'Austrailia',
    average: 82,
    male: 80,
    female: 84,
  },
  {
    name: 'Austria',
    average: 81,
    male: 78,
    female: 84,
  },
  {
    name: 'Azerbaijan',
    average: 74,
    male: 72,
    female: 77,
  },
  {
    name: 'Bahamas',
    average: 74,
    male: 71,
    female: 77,
  },
  {
    name: 'Bahrain',
    average: 76,
    male: 75,
    female: 76,
  },
  {
    name: 'Bangladesh',
    average: 71,
    male: 70,
    female: 71,
  },
  {
    name: 'Barbados',
    average: 75,
    male: 73,
    female: 78,
  },
  {
    name: 'Belarus',
    average: 73,
    male: 67,
    female: 78,
  },
  {
    name: 'Belgium',
    average: 80,
    male: 78,
    female: 83,
  },
  {
    name: 'Belize',
    average: 74,
    male: 71,
    female: 77,
  },
  {
    name: 'Benin',
    average: 59,
    male: 58,
    female: 61,
  },
  {
    name: 'Bhutan',
    average: 68,
    male: 68,
    female: 69,
  },
  {
    name: 'Bolivia',
    average: 67,
    male: 65,
    female: 69,
  },
  {
    name: 'Bosnia-Herzegovina',
    average: 75,
    male: 72,
    female: 78,
  },
  {
    name: 'Botswana',
    average: 64,
    male: 62,
    female: 67,
  },
  {
    name: 'Brazil',
    average: 75,
    male: 71,
    female: 79,
  },
  {
    name: 'Brunei',
    average: 79,
    male: 77,
    female: 80,
  },
  {
    name: 'Bulgaria',
    average: 75,
    male: 71,
    female: 78,
  },
  {
    name: 'Burkina Faso',
    average: 56,
    male: 56,
    female: 57,
  },
  {
    name: 'Burundi',
    average: 59,
    male: 57,
    female: 61,
  },
  {
    name: 'Cambodia',
    average: 64,
    male: 61,
    female: 66,
  },
  {
    name: 'Cameroon',
    average: 57,
    male: 56,
    female: 58,
  },
  {
    name: 'Canada',
    average: 81,
    male: 79,
    female: 84,
  },
  {
    name: 'Cape Verde',
    average: 75,
    male: 71,
    female: 80,
  },
  {
    name: 'Central African Republic',
    average: 50,
    male: 48,
    female: 52,
  },
  {
    name: 'Chad',
    average: 51,
    male: 50,
    female: 52,
  },
  {
    name: 'Channel Islands',
    average: 82,
    male: 80,
    female: 85,
  },
  {
    name: 'Chile',
    average: 79,
    male: 76,
    female: 81,
  },
  {
    name: 'China',
    average: 75,
    male: 73,
    female: 78,
  },
  {
    name: 'Colombia',
    average: 75,
    male: 72,
    female: 79,
  },
  {
    name: 'Comoros',
    average: 61,
    male: 60,
    female: 62,
  },
  {
    name: 'Congo',
    average: 58,
    male: 57,
    female: 59,
  },
  {
    name: 'Congo, Dem. Rep. of',
    average: 50,
    male: 48,
    female: 52,
  },
  {
    name: 'Costa Rica',
    average: 79,
    male: 77,
    female: 82,
  },
  {
    name: "Cote d'Ivoire",
    average: 51,
    male: 50,
    female: 52,
  },
  {
    name: 'Croatia',
    average: 77,
    male: 74,
    female: 81,
  },
  {
    name: 'Cuba',
    average: 78,
    male: 77,
    female: 80,
  },
  {
    name: 'Curacao',
    average: 78,
    male: 75,
    female: 81,
  },
  {
    name: 'Cyprus',
    average: 80,
    male: 78,
    female: 82,
  },
  {
    name: 'Czech Republic',
    average: 79,
    male: 76,
    female: 82,
  },
  {
    name: 'Denmark',
    average: 81,
    male: 79,
    female: 83,
  },
  {
    name: 'Djibouti',
    average: 62,
    male: 60,
    female: 63,
  },
  {
    name: 'Dominica',
    average: 75,
    male: 72,
    female: 77,
  },
  {
    name: 'Dominican Republic',
    average: 73,
    male: 70,
    female: 77,
  },
  {
    name: 'Ecuador',
    average: 75,
    male: 72,
    female: 78,
  },
  {
    name: 'Egypt',
    average: 71,
    male: 70,
    female: 73,
  },
  {
    name: 'El Salvador',
    average: 73,
    male: 68,
    female: 77,
  },
  {
    name: 'Equatorial Guinea',
    average: 57,
    male: 56,
    female: 59,
  },
  {
    name: 'Eritrea',
    average: 63,
    male: 60,
    female: 65,
  },
  {
    name: 'Estonia',
    average: 77,
    male: 73,
    female: 81,
  },
  {
    name: 'Ethiopia',
    average: 64,
    male: 62,
    female: 65,
  },
  {
    name: 'Federated States of Micronesia',
    average: 70,
    male: 69,
    female: 72,
  },
  {
    name: 'Fiji',
    average: 70,
    male: 67,
    female: 73,
  },
  {
    name: 'Finland',
    average: 81,
    male: 78,
    female: 84,
  },
  {
    name: 'France',
    average: 82,
    male: 79,
    female: 85,
  },
  {
    name: 'French Guiana',
    average: 80,
    male: 77,
    female: 83,
  },
  {
    name: 'French Polynesia',
    average: 77,
    male: 75,
    female: 79,
  },
  {
    name: 'Gabon',
    average: 63,
    male: 62,
    female: 64,
  },
  {
    name: 'Gambia',
    average: 59,
    male: 58,
    female: 60,
  },
  {
    name: 'Georgia',
    average: 75,
    male: 71,
    female: 79,
  },
  {
    name: 'Germany',
    average: 80,
    male: 78,
    female: 83,
  },
  {
    name: 'Ghana',
    average: 61,
    male: 60,
    female: 63,
  },
  {
    name: 'Greece',
    average: 81,
    male: 78,
    female: 83,
  },
  {
    name: 'Grenada',
    average: 76,
    male: 74,
    female: 79,
  },
  {
    name: 'Guadeloupe',
    average: 81,
    male: 78,
    female: 84,
  },
  {
    name: 'Guam',
    average: 79,
    male: 76,
    female: 82,
  },
  {
    name: 'Guatemala',
    average: 73,
    male: 69,
    female: 76,
  },
  {
    name: 'Guinea',
    average: 60,
    male: 58,
    female: 61,
  },
  {
    name: 'Guinea-Bissau',
    average: 54,
    male: 53,
    female: 56,
  },
  {
    name: 'Guyana',
    average: 66,
    male: 64,
    female: 69,
  },
  {
    name: 'Haiti',
    average: 64,
    male: 61,
    female: 65,
  },
  {
    name: 'Honduras',
    average: 74,
    male: 72,
    female: 76,
  },
  {
    name: 'Hong Kong, SAR',
    average: 84,
    male: 81,
    female: 87,
  },
  {
    name: 'Hungary',
    average: 76,
    male: 72,
    female: 79,
  },
  {
    name: 'Iceland',
    average: 82,
    male: 81,
    female: 84,
  },
  {
    name: 'India',
    average: 68,
    male: 66,
    female: 69,
  },
  {
    name: 'Indonesia',
    average: 71,
    male: 69,
    female: 73,
  },
  {
    name: 'Iran',
    average: 74,
    male: 72,
    female: 76,
  },
  {
    name: 'Iraq',
    average: 69,
    male: 67,
    female: 71,
  },
  {
    name: 'Ireland',
    average: 81,
    male: 79,
    female: 83,
  },
  {
    name: 'Israel',
    average: 82,
    male: 80,
    female: 84,
  },
  {
    name: 'Italy',
    average: 83,
    male: 80,
    female: 85,
  },
  {
    name: 'Jamaica',
    average: 74,
    male: 70,
    female: 78,
  },
  {
    name: 'Japan',
    average: 83,
    male: 80,
    female: 87,
  },
  {
    name: 'Jordan',
    average: 74,
    male: 73,
    female: 77,
  },
  {
    name: 'Kazakhstan',
    average: 70,
    male: 66,
    female: 75,
  },
  {
    name: 'Kenya',
    average: 62,
    male: 60,
    female: 65,
  },
  {
    name: 'Kiribati',
    average: 65,
    male: 63,
    female: 68,
  },
  {
    name: 'Korea, North',
    average: 70,
    male: 66,
    female: 74,
  },
  {
    name: 'Korea, South',
    average: 82,
    male: 79,
    female: 85,
  },
  {
    name: 'Kosovo',
    average: 77,
    male: 74,
    female: 79,
  },
  {
    name: 'Kuwait',
    average: 74,
    male: 73,
    female: 76,
  },
  {
    name: 'Kyrgyzstan',
    average: 70,
    male: 66,
    female: 74,
  },
  {
    name: 'Laos',
    average: 68,
    male: 67,
    female: 70,
  },
  {
    name: 'Latvia',
    average: 74,
    male: 70,
    female: 79,
  },
  {
    name: 'Lebanon',
    average: 77,
    male: 76,
    female: 79,
  },
  {
    name: 'Lesotho',
    average: 44,
    male: 43,
    female: 46,
  },
  {
    name: 'Liberia',
    average: 60,
    male: 59,
    female: 61,
  },
  {
    name: 'Libya',
    average: 71,
    male: 69,
    female: 74,
  },
  {
    name: 'Liechtenstein',
    average: 82,
    male: 81,
    female: 84,
  },
  {
    name: 'Lithuania',
    average: 74,
    male: 69,
    female: 79,
  },
  {
    name: 'Luxembourg',
    average: 82,
    male: 80,
    female: 84,
  },
  {
    name: 'Macao, SAR',
    average: 83,
    male: 80,
    female: 86,
  },
  {
    name: 'Macedonia',
    average: 75,
    male: 73,
    female: 77,
  },
  {
    name: 'Madagascar',
    average: 65,
    male: 64,
    female: 66,
  },
  {
    name: 'Malawi',
    average: 61,
    male: 60,
    female: 62,
  },
  {
    name: 'Malaysia',
    average: 75,
    male: 73,
    female: 77,
  },
  {
    name: 'Maldives',
    average: 74,
    male: 73,
    female: 75,
  },
  {
    name: 'Mali',
    average: 53,
    male: 53,
    female: 53,
  },
  {
    name: 'Malta',
    average: 82,
    male: 80,
    female: 84,
  },
  {
    name: 'Marshall Islands',
    average: 72,
    male: 70,
    female: 75,
  },
  {
    name: 'Martinique',
    average: 82,
    male: 79,
    female: 85,
  },
  {
    name: 'Mauritania',
    average: 63,
    male: 62,
    female: 64,
  },
  {
    name: 'Mauritius',
    average: 74,
    male: 71,
    female: 78,
  },
  {
    name: 'Mayotte',
    average: 79,
    male: 76,
    female: 83,
  },
  {
    name: 'Mexico',
    average: 75,
    male: 73,
    female: 78,
  },
  {
    name: 'Moldova',
    average: 72,
    male: 68,
    female: 76,
  },
  {
    name: 'Mongolia',
    average: 69,
    male: 65,
    female: 75,
  },
  {
    name: 'Montenegro',
    average: 77,
    male: 74,
    female: 79,
  },
  {
    name: 'Morocco',
    average: 74,
    male: 73,
    female: 75,
  },
  {
    name: 'Mozambique',
    average: 54,
    male: 52,
    female: 56,
  },
  {
    name: 'Myanmar',
    average: 65,
    male: 63,
    female: 67,
  },
  {
    name: 'Namibia',
    average: 64,
    male: 62,
    female: 67,
  },
  {
    name: 'Nauru',
    average: 66,
    male: 62,
    female: 70,
  },
  {
    name: 'Nepal',
    average: 67,
    male: 66,
    female: 69,
  },
  {
    name: 'Netherlands',
    average: 81,
    male: 79,
    female: 83,
  },
  {
    name: 'New Caledonia',
    average: 77,
    male: 74,
    female: 81,
  },
  {
    name: 'New Zealand',
    average: 81,
    male: 80,
    female: 83,
  },
  {
    name: 'Nicaragua',
    average: 75,
    male: 72,
    female: 78,
  },
  {
    name: 'Niger',
    average: 60,
    male: 59,
    female: 61,
  },
  {
    name: 'Nigeria',
    average: 52,
    male: 52,
    female: 53,
  },
  {
    name: 'Norway',
    average: 82,
    male: 80,
    female: 84,
  },
  {
    name: 'Oman',
    average: 77,
    male: 75,
    female: 79,
  },
  {
    name: 'Pakistan',
    average: 66,
    male: 66,
    female: 67,
  },
  {
    name: 'Palau',
    average: 72,
    male: 69,
    female: 76,
  },
  {
    name: 'Palestinian Territory',
    average: 73,
    male: 72,
    female: 75,
  },
  {
    name: 'Panama',
    average: 78,
    male: 75,
    female: 80,
  },
  {
    name: 'Papua New Guinea',
    average: 62,
    male: 60,
    female: 65,
  },
  {
    name: 'Paraguay',
    average: 72,
    male: 70,
    female: 74,
  },
  {
    name: 'Peru',
    average: 75,
    male: 72,
    female: 78,
  },
  {
    name: 'Philippines',
    average: 69,
    male: 65,
    female: 72,
  },
  {
    name: 'Poland',
    average: 78,
    male: 74,
    female: 82,
  },
  {
    name: 'Portugal',
    average: 80,
    male: 77,
    female: 83,
  },
  {
    name: 'Puerto Rico',
    average: 79,
    male: 76,
    female: 83,
  },
  {
    name: 'Qatar',
    average: 78,
    male: 78,
    female: 79,
  },
  {
    name: 'Reunion',
    average: 80,
    male: 77,
    female: 84,
  },
  {
    name: 'Romania',
    average: 75,
    male: 71,
    female: 78,
  },
  {
    name: 'Russia',
    average: 71,
    male: 65,
    female: 76,
  },
  {
    name: 'Rwanda',
    average: 65,
    male: 63,
    female: 66,
  },
  {
    name: 'Samoa',
    average: 74,
    male: 73,
    female: 76,
  },
  {
    name: 'San Marino',
    average: 87,
    male: 84,
    female: 89,
  },
  {
    name: 'Sao Tome and Principe',
    average: 66,
    male: 64,
    female: 68,
  },
  {
    name: 'Saudi Arabia',
    average: 74,
    male: 73,
    female: 75,
  },
  {
    name: 'Senegal',
    average: 65,
    male: 63,
    female: 67,
  },
  {
    name: 'Serbia',
    average: 75,
    male: 73,
    female: 78,
  },
  {
    name: 'Seychelles',
    average: 73,
    male: 69,
    female: 78,
  },
  {
    name: 'Sierra Leone',
    average: 50,
    male: 50,
    female: 51,
  },
  {
    name: 'Singapore',
    average: 83,
    male: 80,
    female: 85,
  },
  {
    name: 'Slovakia',
    average: 76,
    male: 73,
    female: 80,
  },
  {
    name: 'Slovenia',
    average: 81,
    male: 78,
    female: 84,
  },
  {
    name: 'Solomon Islands',
    average: 70,
    male: 67,
    female: 74,
  },
  {
    name: 'Somalia',
    average: 55,
    male: 53,
    female: 57,
  },
  {
    name: 'South Africa',
    average: 61,
    male: 59,
    female: 63,
  },
  {
    name: 'South Sudan',
    average: 55,
    male: 54,
    female: 56,
  },
  {
    name: 'Spain',
    average: 83,
    male: 80,
    female: 86,
  },
  {
    name: 'Sri Lanka',
    average: 74,
    male: 71,
    female: 77,
  },
  {
    name: 'St. Kitts-Nevis',
    average: 75,
    male: 73,
    female: 78,
  },
  {
    name: 'St. Lucia',
    average: 79,
    male: 75,
    female: 83,
  },
  {
    name: 'St. Vincent & the Grenadines',
    average: 71,
    male: 70,
    female: 74,
  },
  {
    name: 'Sudan',
    average: 62,
    male: 60,
    female: 64,
  },
  {
    name: 'Suriname',
    average: 71,
    male: 68,
    female: 74,
  },
  {
    name: 'Swaziland',
    average: 49,
    male: 50,
    female: 48,
  },
  {
    name: 'Sweden',
    average: 82,
    male: 80,
    female: 84,
  },
  {
    name: 'Switzerland',
    average: 83,
    male: 81,
    female: 85,
  },
  {
    name: 'Syria',
    average: 70,
    male: 64,
    female: 76,
  },
  {
    name: 'Taiwan',
    average: 80,
    male: 77,
    female: 83,
  },
  {
    name: 'Tajikistan',
    average: 67,
    male: 64,
    female: 71,
  },
  {
    name: 'Tanzania',
    average: 62,
    male: 60,
    female: 63,
  },
  {
    name: 'Thailand',
    average: 75,
    male: 72,
    female: 78,
  },
  {
    name: 'Timor-Leste',
    average: 68,
    male: 66,
    female: 69,
  },
  {
    name: 'Togo',
    average: 57,
    male: 56,
    female: 57,
  },
  {
    name: 'Tonga',
    average: 76,
    male: 74,
    female: 77,
  },
  {
    name: 'Trinidad and Tobago',
    average: 75,
    male: 71,
    female: 78,
  },
  {
    name: 'Tunisia',
    average: 76,
    male: 74,
    female: 78,
  },
  {
    name: 'Turkey',
    average: 77,
    male: 75,
    female: 79,
  },
  {
    name: 'Turkmenistan',
    average: 65,
    male: 61,
    female: 70,
  },
  {
    name: 'Tuvalu',
    average: 70,
    male: 67,
    female: 72,
  },
  {
    name: 'Uganda',
    average: 59,
    male: 58,
    female: 60,
  },
  {
    name: 'Ukraine',
    average: 71,
    male: 66,
    female: 76,
  },
  {
    name: 'United Arab Emirates',
    average: 77,
    male: 76,
    female: 78,
  },
  {
    name: 'United Kingdom',
    average: 81,
    male: 79,
    female: 83,
  },
  {
    name: 'Uruguay',
    average: 77,
    male: 73,
    female: 80,
  },
  {
    name: 'Uzbekistan',
    average: 68,
    male: 65,
    female: 72,
  },
  {
    name: 'Vanuatu',
    average: 71,
    male: 70,
    female: 73,
  },
  {
    name: 'Venezuela',
    average: 75,
    male: 72,
    female: 78,
  },
  {
    name: 'Vietnam',
    average: 73,
    male: 71,
    female: 76,
  },
  {
    name: 'Western Sahara',
    average: 68,
    male: 66,
    female: 70,
  },
  {
    name: 'Yemen',
    average: 65,
    male: 62,
    female: 67,
  },
  {
    name: 'Zambia',
    average: 53,
    male: 51,
    female: 56,
  },
  {
    name: 'Zimbabwe',
    average: 61,
    male: 60,
    female: 62,
  },
];

module.exports = countryStats;
